### ISSUE TITLE
Scrolling Main Menu

### ISSUE THREAD

**Issue by swill** [cloudops/cca-website#8]
Ideally, instead of the main menu fading away on scroll, it should scroll off the top of the page so it behaves more naturally with the action being performed.

**Comment by Cdaoustd** [comment]
Alright! I will fix that tomorrow as well

**Comment by Cdaoustd** [comment]
I changed it to what I think you meant (it's in the pr) but can you please just confirm that this is the behaviour you want?

**Comment by swill** [comment]
Yep, perfect.  Thanks...  :)
